#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx

# Custom index.html page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# 301 Redirect
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/oyendekingz permanent;/" /etc/nginx/sites-enabled/default

# Ngix start
service nginx start