#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
# Custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx

# Custom index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# 301 Redirect
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/oyendekingz permanent;/" /etc/nginx/sites-enabled/default

# 404 Page Creation
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
the_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$the_string/" /etc/nginx/sites-enabled/default

# Ngix restart
sudo service nginx restart
