#!/usr/bin/env bash
# Script that installs Nginx server and customizes 404 not found
sudo apt-get -y update
sudo apt-get -y install nginx
# Custom html page message
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
# Redirects /redirect_me
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/oyendekingz permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-enabled/default
# Nginx Restart
sudo service nginx restart